model:
  backbone:
    class_path: src.models.architectures.ViTFocusRegressor
    init_args:
      version: vit_b_16
      pretrained: true
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.0001
    weight_decay: 0.01
lr_scheduler:
  class_path: torch.optim.lr_scheduler.CosineAnnealingLR
  init_args:
    T_max: 100
    eta_min: 1e-6
